name: Purge jsDelivr cache

on:
  push:
    branches:
      - main
    paths:
      - 'js/carousel-splide-json.json'

jobs:
  purge-jsdelivr:
    runs-on: ubuntu-latest
    steps:
      - name: Purge jsDelivr cache
        uses: gacts/purge-jsdelivr-cache@v1
        with:
          url: https://cdn.jsdelivr.net/gh/raulgonzalez77/ellucian-experience-files@main/js/carousel-splide-json.json
